### ISSUE TITLE
Startup Crash

### ISSUE THREAD

**Issue by GershonR** [TheoKah/CarrotShop#42]
spongeforge-1.12.2-2705-7.1.0-BETA-3374
CarrotShop-1.17-S7.0-MC1.12.2
forge-1.12.2-14.23.4.2738-universal

I sometimes get this crash on startup, it does not always happen so it is difficult to reproduce.

```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  SpongeCoremod (spongeforge-1.12.2-2705-7.1.0-BETA-3374.jar)
Contact their authors BEFORE contacting forge

// Sorry :(

Time: 8/5/18 11:03 PM
Description: Watching Server

java.lang.Error: ServerHangWatchdog detected that a single server tick took 60.00 seconds (should be max 0.05)
	at org.spongepowered.common.event.tracking.phase.tick.TickPhase$Tick.<clinit>(TickPhase.java:39)
	at net.minecraft.world.WorldServer.func_180495_p(WorldServer.java:3310)
	at net.minecraft.tileentity.TileEntity.func_70296_d(TileEntity.java:157)
	at org.spongepowered.common.data.processor.data.tileentity.TileEntitySignDataProcessor.set(TileEntitySignDataProcessor.java:81)
	at org.spongepowered.common.data.processor.data.tileentity.TileEntitySignDataProcessor.set(TileEntitySignDataProcessor.java:54)
	at org.spongepowered.common.data.processor.common.AbstractSingleDataSingleTargetProcessor.set(AbstractSingleDataSingleTargetProcessor.java:88)
	at org.spongepowered.common.data.util.DataProcessorDelegate.set(DataProcessorDelegate.java:179)
	at net.minecraft.tileentity.TileEntity.offer(TileEntity.java:768)
	at net.minecraft.tileentity.TileEntity.offer(TileEntity.java:644)
	at org.spongepowered.api.data.value.mutable.CompositeValueStore.offer(CompositeValueStore.java:228)
	at com.carrot.carrotshop.shop.Shop.setFirstLineColor(Shop.java:192)
	at com.carrot.carrotshop.shop.Shop.setOK(Shop.java:111)
	at com.carrot.carrotshop.shop.Shop.update(Shop.java:67)
	at com.carrot.carrotshop.ShopsData.pushShop(ShopsData.java:188)
	at com.carrot.carrotshop.ShopsData.load(ShopsData.java:85)
	at com.carrot.carrotshop.CarrotShop.onStart(CarrotShop.java:73)
	at org.spongepowered.common.event.listener.GameStartedServerEventListener_CarrotShop_onStart15.handle(Unknown Source)
	at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95)
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:383)
	at org.spongepowered.mod.event.SpongeModEventManager.extendedPost(SpongeModEventManager.java:443)
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:404)
	at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:231)
	at org.spongepowered.mod.SpongeMod.onStateEvent(SpongeMod.java:271)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.redirect$onPost$zza000(LoadController.java:560)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
	at net.minecraftforge.fml.common.Loader.serverStarted(Loader.java:807)
	at net.minecraftforge.fml.common.FMLCommonHandler.handleServerStarted(FMLCommonHandler.java:301)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:488)
	at java.lang.Thread.run(Thread.java:748)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server Watchdog
Stacktrace:
	at org.spongepowered.common.event.tracking.phase.tick.TickPhase$Tick.<clinit>(TickPhase.java:39)
	at net.minecraft.world.WorldServer.func_180495_p(WorldServer.java:3310)
	at net.minecraft.tileentity.TileEntity.func_70296_d(TileEntity.java:157)
	at org.spongepowered.common.data.processor.data.tileentity.TileEntitySignDataProcessor.set(TileEntitySignDataProcessor.java:81)
	at org.spongepowered.common.data.processor.data.tileentity.TileEntitySignDataProcessor.set(TileEntitySignDataProcessor.java:54)
	at org.spongepowered.common.data.processor.common.AbstractSingleDataSingleTargetProcessor.set(AbstractSingleDataSingleTargetProcessor.java:88)
	at org.spongepowered.common.data.util.DataProcessorDelegate.set(DataProcessorDelegate.java:179)
	at net.minecraft.tileentity.TileEntity.offer(TileEntity.java:768)
	at net.minecraft.tileentity.TileEntity.offer(TileEntity.java:644)
	at org.spongepowered.api.data.value.mutable.CompositeValueStore.offer(CompositeValueStore.java:228)
	at com.carrot.carrotshop.shop.Shop.setFirstLineColor(Shop.java:192)
	at com.carrot.carrotshop.shop.Shop.setOK(Shop.java:111)
	at com.carrot.carrotshop.shop.Shop.update(Shop.java:67)
	at com.carrot.carrotshop.ShopsData.pushShop(ShopsData.java:188)
	at com.carrot.carrotshop.ShopsData.load(ShopsData.java:85)
	at com.carrot.carrotshop.CarrotShop.onStart(CarrotShop.java:73)
	at org.spongepowered.common.event.listener.GameStartedServerEventListener_CarrotShop_onStart15.handle(Unknown Source)
	at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95)
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:383)
	at org.spongepowered.mod.event.SpongeModEventManager.extendedPost(SpongeModEventManager.java:443)
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:404)
	at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:231)
	at org.spongepowered.mod.SpongeMod.onStateEvent(SpongeMod.java:271)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.redirect$onPost$zza000(LoadController.java:560)
```

**Comment by TheoKah** [comment]
Sorry for late answer.

Is this still occurring?

**Comment by TheoKah** [comment]
Closing as no answer. Feel free to re-open if this is still a problem
