### ISSUE TITLE
Shop reports issue.

### ISSUE THREAD

**Issue by HaoSs07B** [TheoKah/CarrotShop#65]
The report never gets generated.
Running latest carrotshop from github, sponge version 3616

com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 12 path $
at com.google.gson.JsonParser.parse(JsonParser.java:65) ~[JsonParser.class:?]
at com.google.gson.JsonParser.parse(JsonParser.java:45) ~[JsonParser.class:?]
at com.carrot.carrotshop.ShopsLogs.lambda$generateReport$0(ShopsLogs.java:246) ~[ShopsLogs.class:?]
at org.spongepowered.api.scheduler.Task$Builder.lambda$execute$0(Task.java:139) ~[Task$Builder.class:1.12.2-2768-7.1.6-RC3616]
at org.spongepowered.common.scheduler.SchedulerBase.lambda$startTask$0(SchedulerBase.java:192) ~[SchedulerBase.class:1.12.2-2768-7.1.6-RC3616]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_201]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_201]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_201]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_201]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
Caused by: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 12 path $
at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1559) ~[JsonReader.class:?]
at com.google.gson.stream.JsonReader.checkLenient(JsonReader.java:1401) ~[JsonReader.class:?]
at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:542) ~[JsonReader.class:?]
at com.google.gson.stream.JsonReader.peek(JsonReader.java:425) ~[JsonReader.class:?]
at com.google.gson.JsonParser.parse(JsonParser.java:60) ~[JsonParser.class:?]
... 9 more

**Comment by TheoKah** [comment]
This is the second report I have today about this. This is probably due to a sponge/lib upgrade.
I'll see if I can address the problem tonight

**Comment by TheoKah** [comment]
This was an issue due to https certificates.
Should be good now.

**Comment by HaoSs07B** [comment]
Reports now generate but they are still empty
http://carrotshop.xyz/6562049937361687839.htm

**Comment by TheoKah** [comment]
This was another problem due to the backend server. This report is broken, but new ones should work.

**Comment by HaoSs07B** [comment]
Looks like the issue is now solved, thank you!
